development:
  access_key:
    IAmSeekingJamaharon
  secret_key:
    ThereAreFourLights!!!
  queue_region:
    us-east-1
  queue_name:
    test_queue

test:
  access_key:
    IAmSeekingJamaharon
  secret_key:
    ThereAreFourLights!!!
  queue_region:
    us-east-1
  queue_name:
    test_queue